name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger only when a tag starting with 'v' is pushed, e.g., 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Adjust according to your project's target framework

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish Single Executable
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o ./publish

      - name: Rename Executable
        run: |
          $exeName = Get-ChildItem ./publish/*.exe | Select-Object -ExpandProperty Name
          Rename-Item -Path "./publish/$exeName" -NewName "app.exe"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./publish/app.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
